export const header = {
  name: "Deal List",
  description: "",
  renders: ["application/json", "text/html"],
  parses: [
    "application/json",
    "application/x-www-form-urlencoded",
    "multipart/form-data",
  ],
  actions: {
    POST: {
      pk: {
        type: "integer",
        required: false,
        read_only: true,
        label: "ID",
      },
      owner: {
        type: "string",
        required: false,
        read_only: true,
        label: "Owner",
      },
      created_by: {
        type: "string",
        required: false,
        read_only: true,
        label: "Created by",
      },
      updated_by: {
        type: "string",
        required: false,
        read_only: true,
        label: "Updated by",
      },
      created_at: {
        type: "string",
        required: false,
        read_only: true,
        label: "Created at",
      },
      updated_at: {
        type: "string",
        required: false,
        read_only: true,
        label: "Updated at",
      },
      deal_name: {
        type: "string",
        required: true,
        read_only: false,
        label: "Deal",
        max_length: 255,
      },
      amount: {
        type: "decimal",
        required: false,
        read_only: false,
        label: "数量",
        max_digits: 10,
        decimal_places: 5,
      },
      expected_revenue: {
        type: "decimal",
        required: false,
        read_only: false,
        label: "预期收入",
        max_digits: 10,
        decimal_places: 2,
      },
      closing_date: {
        type: "datetime",
        required: true,
        read_only: false,
        label: "完成时间",
      },
      description: {
        type: "string",
        required: false,
        read_only: false,
        label: "详情",
      },
      contact: {
        type: "nested object",
        required: false,
        read_only: true,
        label: "Contact",
        children: {
          pk: {
            type: "integer",
            required: false,
            read_only: true,
            label: "ID",
          },
          owner: {
            type: "string",
            required: false,
            read_only: true,
            label: "Owner",
          },
          created_by: {
            type: "string",
            required: false,
            read_only: true,
            label: "Created by",
          },
          updated_by: {
            type: "string",
            required: false,
            read_only: true,
            label: "Updated by",
          },
          created_at: {
            type: "string",
            required: false,
            read_only: true,
            label: "Created at",
          },
          updated_at: {
            type: "string",
            required: false,
            read_only: true,
            label: "Updated at",
          },
          id: {
            type: "integer",
            required: false,
            read_only: true,
            label: "ID",
          },
          first_name: {
            type: "string",
            required: false,
            read_only: false,
            label: "First name",
            max_length: 255,
          },
          last_name: {
            type: "string",
            required: false,
            read_only: false,
            label: "Last name",
            max_length: 255,
          },
          title: {
            type: "string",
            required: false,
            read_only: false,
            label: "Title",
            max_length: 255,
          },
          email: {
            type: "email",
            required: false,
            read_only: false,
            label: "Email",
            max_length: 254,
          },
          mobile: {
            type: "string",
            required: false,
            read_only: false,
            label: "Mobile",
            max_length: 255,
          },
          phone: {
            type: "string",
            required: false,
            read_only: false,
            label: "Phone",
            max_length: 255,
          },
          custom_fields: {
            type: "field",
            required: false,
            read_only: false,
            label: "Custom fields",
          },
        },
      },
      contract: {
        type: "nested object",
        required: false,
        read_only: false,
        label: "Contract",
        children: {
          pk: {
            type: "integer",
            required: false,
            read_only: true,
            label: "ID",
          },
          owner: {
            type: "string",
            required: false,
            read_only: true,
            label: "Owner",
          },
          created_by: {
            type: "string",
            required: false,
            read_only: true,
            label: "Created by",
          },
          updated_by: {
            type: "string",
            required: false,
            read_only: true,
            label: "Updated by",
          },
          created_at: {
            type: "string",
            required: false,
            read_only: true,
            label: "Created at",
          },
          updated_at: {
            type: "string",
            required: false,
            read_only: true,
            label: "Updated at",
          },
          contract_code: {
            type: "string",
            required: true,
            read_only: false,
            label: "合同编号",
            max_length: 255,
          },
          contract_date: {
            type: "date",
            required: true,
            read_only: false,
            label: "合同签订日期",
          },
          orders: {
            type: "field",
            required: false,
            read_only: false,
            label: "Orders",
            child: {
              type: "nested object",
              required: false,
              read_only: false,
              children: {
                pk: {
                  type: "integer",
                  required: false,
                  read_only: true,
                  label: "ID",
                },
                owner: {
                  type: "string",
                  required: false,
                  read_only: true,
                  label: "Owner",
                },
                created_by: {
                  type: "string",
                  required: false,
                  read_only: true,
                  label: "Created by",
                },
                updated_by: {
                  type: "string",
                  required: false,
                  read_only: true,
                  label: "Updated by",
                },
                created_at: {
                  type: "string",
                  required: false,
                  read_only: true,
                  label: "Created at",
                },
                updated_at: {
                  type: "string",
                  required: false,
                  read_only: true,
                  label: "Updated at",
                },
                order_code: {
                  type: "string",
                  required: false,
                  read_only: false,
                  label: "生产编号",
                  max_length: 100,
                },
                etd: {
                  type: "date",
                  required: true,
                  read_only: false,
                  label: "预计发货日期",
                },
                deposit: {
                  type: "decimal",
                  required: false,
                  read_only: false,
                  label: "定金",
                  max_digits: 10,
                  decimal_places: 5,
                },
                balance: {
                  type: "decimal",
                  required: false,
                  read_only: false,
                  label: "余额",
                  max_digits: 10,
                  decimal_places: 5,
                },
                destination_port: {
                  type: "string",
                  required: false,
                  read_only: false,
                  label: "目的港口",
                  max_length: 100,
                },
                products: {
                  type: "field",
                  required: false,
                  read_only: false,
                  label: "Products",
                  child: {
                    type: "nested object",
                    required: false,
                    read_only: false,
                    children: {
                      pk: {
                        type: "integer",
                        required: false,
                        read_only: true,
                        label: "ID",
                      },
                      owner: {
                        type: "string",
                        required: false,
                        read_only: true,
                        label: "Owner",
                      },
                      created_by: {
                        type: "string",
                        required: false,
                        read_only: true,
                        label: "Created by",
                      },
                      updated_by: {
                        type: "string",
                        required: false,
                        read_only: true,
                        label: "Updated by",
                      },
                      created_at: {
                        type: "string",
                        required: false,
                        read_only: true,
                        label: "Created at",
                      },
                      updated_at: {
                        type: "string",
                        required: false,
                        read_only: true,
                        label: "Updated at",
                      },
                      product_name: {
                        type: "string",
                        required: true,
                        read_only: false,
                        label: "产品名称",
                        max_length: 255,
                      },
                      product_code: {
                        type: "string",
                        required: false,
                        read_only: false,
                        label: "产品代码",
                        max_length: 255,
                      },
                      product_type: {
                        type: "string",
                        required: false,
                        read_only: false,
                        label: "产品类型",
                        max_length: 255,
                      },
                      packaging: {
                        type: "string",
                        required: false,
                        read_only: false,
                        label: "包装类型",
                        max_length: 255,
                      },
                      size: {
                        type: "string",
                        required: false,
                        read_only: false,
                        label: "规格",
                        max_length: 100,
                      },
                      glazing: {
                        type: "decimal",
                        required: false,
                        read_only: false,
                        label: "冰衣服比例",
                        max_digits: 10,
                        decimal_places: 5,
                      },
                      quantity: {
                        type: "integer",
                        required: false,
                        read_only: false,
                        label: "数量",
                        min_value: -2147483648,
                        max_value: 2147483647,
                      },
                      list_price: {
                        type: "decimal",
                        required: false,
                        read_only: false,
                        label: "价格",
                        max_digits: 10,
                        decimal_places: 5,
                      },
                      discount: {
                        type: "decimal",
                        required: false,
                        read_only: false,
                        label: "折扣",
                        max_digits: 10,
                        decimal_places: 5,
                      },
                      progress_quantity: {
                        type: "integer",
                        required: false,
                        read_only: false,
                        label: "进度数量",
                        min_value: -2147483648,
                        max_value: 2147483647,
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
};

export const data = [
    {
        "pk": 2,
        "owner": "coolister",
        "created_by": "coolister",
        "updated_by": null,
        "created_at": "2024-11-07 06:13:26.130683+00:00",
        "updated_at": "2024-11-07 06:13:26.130692+00:00",
        "deal_name": "New Deal",
        "amount": null,
        "expected_revenue": null,
        "closing_date": "2024-10-10T00:00:00Z",
        "description": "",
        "contact": null,
        "contract": {
            "pk": 2,
            "created_by": null,
            "updated_by": null,
            "created_at": "2024-11-07 06:13:26.134024+00:00",
            "updated_at": "2024-11-07 06:13:26.134030+00:00",
            "contract_code": "Contract_002",
            "contract_date": "2024-01-01",
            "orders": [
                {
                    "pk": 2,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2024-11-07 06:13:26.136102+00:00",
                    "updated_at": "2024-11-07 06:13:26.136111+00:00",
                    "order_code": "Order_002",
                    "etd": "2024-01-01",
                    "deposit": null,
                    "balance": null,
                    "destination_port": null,
                    "products": [
                        {
                            "pk": 2,
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2024-11-07 06:13:26.139320+00:00",
                            "updated_at": "2024-11-07 06:13:26.139326+00:00",
                            "product_name": "Product B",
                            "product_code": null,
                            "product_type": null,
                            "packaging": null,
                            "size": null,
                            "glazing": null,
                            "quantity": 5,
                            "list_price": null,
                            "discount": null,
                            "progress_quantity": null
                        }
                    ]
                }
            ]
        }
    },
    {
        "pk": 1,
        "owner": "coolister",
        "created_by": "coolister",
        "updated_by": "coolister",
        "created_at": "2024-11-07 06:11:48.132194+00:00",
        "updated_at": "2024-11-07 06:46:45.622565+00:00",
        "deal_name": "New Deal",
        "amount": null,
        "expected_revenue": null,
        "closing_date": "2024-10-10T00:00:00Z",
        "description": "",
        "contact": null,
        "contract": {
            "pk": 1,
            "created_by": null,
            "updated_by": null,
            "created_at": "2024-11-07 06:11:48.137095+00:00",
            "updated_at": "2024-11-07 06:46:45.629695+00:00",
            "contract_code": "Contract_002",
            "contract_date": "2024-01-01",
            "orders": [
                {
                    "pk": 1,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2024-11-07 06:11:48.139179+00:00",
                    "updated_at": "2024-11-07 06:46:45.632667+00:00",
                    "order_code": "Order_002",
                    "etd": "2024-01-01",
                    "deposit": null,
                    "balance": null,
                    "destination_port": null,
                    "products": [
                        {
                            "pk": 1,
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2024-11-07 06:11:48.141273+00:00",
                            "updated_at": "2024-11-07 06:46:45.635154+00:00",
                            "product_name": "Product B",
                            "product_code": null,
                            "product_type": null,
                            "packaging": null,
                            "size": null,
                            "glazing": null,
                            "quantity": 5,
                            "list_price": null,
                            "discount": null,
                            "progress_quantity": null
                        }
                    ]
                }
            ]
        }
    },
    {
        "pk": 3,
        "created_by": "coolister",
        "updated_by": null,
        "created_at": "2024-11-07 07:07:16.493414+00:00",
        "updated_at": "2024-11-07 07:07:16.493439+00:00",
        "deal_name": "New Deal",
        "amount": null,
        "expected_revenue": null,
        "closing_date": "2024-10-10T00:00:00Z",
        "description": "",
        "contact": null,
        "contract": {
            "pk": 3,
            "created_by": null,
            "updated_by": null,
            "created_at": "2024-11-07 07:07:16.502559+00:00",
            "updated_at": "2024-11-07 07:07:16.502569+00:00",
            "contract_code": "Contract_002",
            "contract_date": "2024-01-01",
            "orders": [
                {
                    "pk": 3,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2024-11-07 07:07:16.505744+00:00",
                    "updated_at": "2024-11-07 07:07:16.505768+00:00",
                    "order_code": "Order_002",
                    "etd": "2024-01-01",
                    "deposit": null,
                    "balance": null,
                    "destination_port": null,
                    "products": [
                        {
                            "pk": 3,
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2024-11-07 07:07:16.508301+00:00",
                            "updated_at": "2024-11-07 07:07:16.508308+00:00",
                            "product_name": "Product B",
                            "product_code": null,
                            "product_type": null,
                            "packaging": null,
                            "size": null,
                            "glazing": null,
                            "quantity": 5,
                            "list_price": null,
                            "discount": null,
                            "progress_quantity": null
                        }
                    ]
                }
            ]
        }
    },
    {
        "pk": 4,
        "created_by": "coolister",
        "updated_by": null,
        "created_at": "2024-11-07 07:12:26.720339+00:00",
        "updated_at": "2024-11-07 07:12:26.720348+00:00",
        "deal_name": "New Deal",
        "amount": null,
        "expected_revenue": null,
        "closing_date": "2024-10-10T00:00:00Z",
        "description": "",
        "contact": null,
        "contract": null
    },
    {
        "pk": 5,
        "owner": "coolister",
        "created_by": "coolister",
        "updated_by": "coolister",
        "created_at": "2024-11-07 07:17:28.634912+00:00",
        "updated_at": "2024-11-09 14:31:33.550052+00:00",
        "deal_name": "New Deal",
        "amount": null,
        "expected_revenue": null,
        "closing_date": "2024-10-10T00:00:00Z",
        "description": "",
        "contact": {
            "pk": 1,
            "created_by": "coolister",
            "updated_by": null,
            "created_at": "2024-11-07 08:20:48.974912+00:00",
            "updated_at": "2024-11-07 08:20:48.974933+00:00",
            "id": 1,
            "first_name": "Steven",
            "last_name": "Song",
            "title": "Sale",
            "email": "steven.song@gmail.com",
            "mobile": "",
            "phone": "",
            "custom_fields": null
        },
        "contract": {
            "pk": 4,
            "created_by": null,
            "updated_by": "coolister",
            "created_at": "2024-11-07 08:25:20.051018+00:00",
            "updated_at": "2024-11-09 14:31:33.554340+00:00",
            "contract_code": "Contract-003",
            "contract_date": "2024-10-11",
            "orders": [
                {
                    "pk": 4,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2024-11-07 13:50:21.397083+00:00",
                    "updated_at": "2024-11-09 14:31:33.557828+00:00",
                    "order_code": "Order_002",
                    "etd": "2024-01-01",
                    "deposit": null,
                    "balance": null,
                    "destination_port": null,
                    "products": [
                        {
                            "pk": 4,
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2024-11-07 13:50:21.400035+00:00",
                            "updated_at": "2024-11-09 14:31:33.560217+00:00",
                            "product_name": "Product B",
                            "product_code": null,
                            "product_type": null,
                            "packaging": null,
                            "size": null,
                            "glazing": null,
                            "quantity": 5,
                            "list_price": null,
                            "discount": null,
                            "progress_quantity": null
                        }
                    ]
                },
                {
                    "pk": 5,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2024-11-09 14:31:29.788598+00:00",
                    "updated_at": "2024-11-09 14:31:33.564676+00:00",
                    "order_code": "Order_004",
                    "etd": "2024-01-01",
                    "deposit": null,
                    "balance": null,
                    "destination_port": null,
                    "products": [
                        {
                            "pk": 5,
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2024-11-09 14:31:29.791016+00:00",
                            "updated_at": "2024-11-09 14:31:33.566541+00:00",
                            "product_name": "Product B",
                            "product_code": null,
                            "product_type": null,
                            "packaging": null,
                            "size": null,
                            "glazing": null,
                            "quantity": 5,
                            "list_price": null,
                            "discount": null,
                            "progress_quantity": null
                        }
                    ]
                }
            ]
        }
    }
]