export const exampeData = [
    {
      id: 1,
      field_name: "first_name",
      field_type: "text",
      field_tag: null,
      owner: null,
      is_active: true,
      is_mandatory: true,
      content_type: "contact",
      extra_info: null,
      created_by: "",
    },
    {
      id: 2,
      field_name: "last_name",
      field_type: "text",
      field_tag: null,
      owner: null,
      is_active: true,
      is_mandatory: false,
      content_type: "contact",
      extra_info: null,
      created_by: "",
    },
    {
      id: 3,
      field_name: "title",
      field_type: "text",
      field_tag: null,
      owner: null,
      is_active: true,
      is_mandatory: false,
      content_type: "contact",
      extra_info: null,
      created_by: "",
    },
    {
      id: 4,
      field_name: "email",
      field_type: "email",
      field_tag: null,
      owner: null,
      is_active: true,
      is_mandatory: false,
      content_type: "contact",
      extra_info: null,
      created_by: "",
    },
    {
      id: 5,
      field_name: "mobile",
      field_type: "phone",
      field_tag: null,
      owner: null,
      is_active: true,
      is_mandatory: false,
      content_type: "contact",
      extra_info: null,
      created_by: "",
    },
    {
      id: 6,
      field_name: "phone",
      field_type: "phone",
      field_tag: null,
      owner: null,
      is_active: true,
      is_mandatory: false,
      content_type: "contact",
      extra_info: null,
      created_by: "",
    },
    {
      id: 7,
      field_name: "bank account",
      field_type: "text",
      field_tag: null,
      owner: null,
      is_active: true,
      is_mandatory: false,
      content_type: "contact",
      extra_info: null,
      created_by: "",
    },
  ];